import Link from 'next/link';
import { ArrowLeft, Lock } from 'lucide-react';

export const metadata = {
  title: 'Privacy Policy | Darkpost',
  description: 'Read the Darkpost Privacy Policy — what data we collect, how we use it, and your rights.',
};

const sections = [
  {
    number: '01',
    title: 'Information We Collect',
    subsections: [
      {
        label: 'Information you provide:',
        bullets: [
          'Your Google account email address and display name (collected at sign-up via Google OAuth)',
          'Text confessions you write and post',
          'Voice audio recordings you record and upload',
          'Post metadata: category, timestamp, recording duration, waveform shape data',
        ],
      },
      {
        label: 'Information collected automatically:',
        bullets: [
          'Your internal user ID (generated by our authentication system)',
          'Session cookies (used to keep you logged in)',
          'Basic server logs (standard infrastructure logging via Vercel)',
        ],
      },
      {
        label: 'Information we do NOT collect:',
        bullets: [
          'Your real name (unless you include it in a confession)',
          'Your phone number',
          'Your location or IP address (beyond what hosting providers log automatically)',
          'Payment information (Darkpost is free)',
          'Any data from outside the Darkpost platform',
        ],
        highlight: true,
      },
    ],
  },
  {
    number: '02',
    title: 'How We Use Your Data',
    content: 'We use your data only to operate the platform:',
    bullets: [
      'To authenticate your account and keep you logged in',
      'To display your confessions (anonymously or attributed, per your choice)',
      'To allow you to manage and delete your own posts',
      'To enforce our Terms of Use and respond to reports',
      'To comply with legal obligations',
    ],
    footer: 'We do not sell your data. We do not use your data for advertising. We do not share your data with third parties except as required by law or as described in this policy.',
  },
  {
    number: '03',
    title: 'Anonymous Posting & Your Data',
    content: 'When you post anonymously, your name and account details are hidden from other users. However, your account is still internally associated with your post so that:',
    bullets: [
      'You can see and delete your own posts',
      'We can enforce our content policies',
      'We can respond to valid legal requests',
    ],
    footer: 'Your post will display a randomly generated alias instead of your name. No other user can determine your identity from the public feed.',
  },
  {
    number: '04',
    title: 'Voice Recordings',
    content: `Your voice recordings are stored in encrypted cloud storage (Supabase). They are only accessible to logged-in users of Darkpost. When you delete a voice confession, the audio file is permanently and immediately deleted from storage. We do not process, transcribe, or analyze voice content.`,
  },
  {
    number: '05',
    title: 'Data Retention',
    bullets: [
      'Active posts: stored until you delete them',
      'Deleted posts and audio: permanently deleted immediately upon your request — we do not keep backups of deleted content',
      'Account information: retained while your account is active',
      'Server logs: retained per our hosting provider\'s standard policies (typically 30–90 days)',
    ],
  },
  {
    number: '06',
    title: 'Cookies',
    content: 'Darkpost uses session cookies only, which are required to keep you authenticated while using the platform. We do not use:',
    bullets: [
      'Advertising cookies',
      'Third-party tracking pixels',
      'Analytics cookies (beyond anonymous, aggregated infrastructure stats provided by Vercel)',
    ],
    footer: 'You can disable cookies in your browser settings, but this will prevent you from staying logged in.',
  },
  {
    number: '07',
    title: 'Third-Party Services',
    content: 'Darkpost uses:',
    bullets: [
      'Supabase (database & storage) — your posts and audio are stored on Supabase infrastructure',
      'Google OAuth — used for authentication; Google\'s privacy policy applies to the sign-in flow',
      'Vercel — our hosting platform; standard server logs may be retained by Vercel',
    ],
    footer: 'None of these services receive your content for advertising purposes.',
  },
  {
    number: '08',
    title: 'Your Rights',
    content: 'Depending on where you live, you may have the following rights:',
    bullets: [
      'Right to access: request a copy of your data',
      'Right to deletion: delete your posts via the platform directly; request full account deletion by contacting us',
      'Right to correction: update your account via Google account settings',
      'Right to portability: contact us and we will provide your data in a readable format',
      'Right to object: opt out of any future data processing by deleting your account',
    ],
    footer: 'To exercise any of these rights, contact us at team.automatr@gmail.com.',
  },
  {
    number: '09',
    title: 'GDPR — European Users',
    content: `If you are located in the European Economic Area (EEA), you have additional rights under the General Data Protection Regulation (GDPR). Your data is processed on the lawful basis of contract (to provide the service you signed up for) and legitimate interests (platform security and moderation). You may lodge a complaint with your local data protection authority at any time.`,
  },
  {
    number: '10',
    title: 'COPPA — Children\'s Privacy',
    content: `Darkpost is not directed at children under 18. We do not knowingly collect personal information from anyone under 18. If we become aware that a user is under 18, we will immediately delete their account and all associated data.`,
  },
  {
    number: '11',
    title: 'Security',
    content: `We take reasonable technical measures to protect your data, including encrypted storage and secure authentication. However, no system is completely secure. You use the platform at your own risk. Please do not include sensitive personal information (passwords, financial details, ID numbers) in your confessions.`,
  },
  {
    number: '12',
    title: 'Changes to This Policy',
    content: `We may update this Privacy Policy at any time. We will notify users of material changes by updating the "Last Updated" date. Your continued use of the platform after changes constitutes acceptance of the updated policy.`,
  },
  {
    number: '13',
    title: 'Contact',
    content: 'For any privacy-related questions, data requests, or concerns:',
    bullets: [
      'Email: team.automatr@gmail.com',
      'Platform: darkpost.vercel.app',
    ],
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0e0e0e] text-[#F0ECE3]">
      {/* Header */}
      <header className="sticky top-0 z-30 bg-[#0e0e0e]/90 backdrop-blur-xl border-b border-white/5 px-6 h-14 flex items-center gap-4">
        <Link href="/" className="p-2 hover:bg-white/5 rounded-full transition-colors">
          <ArrowLeft size={18} />
        </Link>
        <span className="font-syne font-bold text-sm uppercase tracking-widest">Privacy Policy</span>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16">
        {/* Hero */}
        <div className="mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-[#ff535b]/10 border border-[#ff535b]/20 mb-6">
            <Lock size={14} className="text-[#ff535b]" />
            <span className="font-syne font-bold text-[11px] uppercase tracking-widest text-[#ff535b]">Legal</span>
          </div>
          <h1 className="font-syne font-extrabold text-4xl md:text-5xl tracking-tighter mb-4">
            Privacy Policy
          </h1>
          <div className="flex items-center gap-4 text-[#4A4A4A] font-inter text-sm">
            <span>Last Updated: April 2025</span>
            <span>·</span>
            <span>Effective Date: April 2025</span>
          </div>
          <p className="mt-6 font-inter text-[#6B6B6B] leading-relaxed max-w-xl">
            This Privacy Policy explains what data Darkpost collects, how it is used, and your rights regarding your data.
          </p>
        </div>

        {/* Terms Link */}
        <div className="mb-12 p-4 rounded-2xl bg-white/[0.03] border border-white/5 flex items-center justify-between">
          <span className="font-inter text-sm text-[#6B6B6B]">Also read our Terms of Use</span>
          <Link href="/terms" className="px-4 py-2 rounded-full bg-[#ff535b]/10 border border-[#ff535b]/20 text-[#ff535b] font-syne font-bold text-xs uppercase tracking-widest hover:bg-[#ff535b]/20 transition-colors">
            View Terms →
          </Link>
        </div>

        {/* Sections */}
        <div className="flex flex-col gap-0">
          {sections.map((section, idx) => (
            <div
              key={idx}
              className="py-8 border-b border-white/5 last:border-0 group"
            >
              <div className="flex gap-6 items-start">
                {/* Number */}
                <span className="font-mono text-[11px] text-[#2a2a2a] pt-1 flex-shrink-0 group-hover:text-[#ff535b]/30 transition-colors">
                  {section.number}
                </span>
                {/* Content */}
                <div className="flex-1">
                  <h2 className="font-syne font-bold text-lg text-[#F0ECE3] mb-3 tracking-tight">
                    {section.title}
                  </h2>
                  {section.content && (
                    <p className="font-inter text-[#6B6B6B] text-sm leading-relaxed mb-3">
                      {section.content}
                    </p>
                  )}
                  {/* Subsections */}
                  {'subsections' in section && section.subsections && section.subsections.map((sub, si) => (
                    <div key={si} className="mb-4">
                      <p className={`font-inter text-xs font-semibold uppercase tracking-widest mb-2 ${sub.highlight ? 'text-green-500/60' : 'text-[#4A4A4A]'}`}>
                        {sub.label}
                      </p>
                      <ul className="flex flex-col gap-2">
                        {sub.bullets.map((bullet, bi) => (
                          <li key={bi} className="flex items-start gap-3 font-inter text-sm text-[#6B6B6B]">
                            <span className={`w-1 h-1 rounded-full mt-2 flex-shrink-0 ${sub.highlight ? 'bg-green-500/40' : 'bg-[#ff535b]/40'}`} />
                            {bullet}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                  {/* Regular bullets */}
                  {'bullets' in section && section.bullets && !('subsections' in section) && (
                    <ul className="flex flex-col gap-2 mb-3">
                      {section.bullets.map((bullet, i) => (
                        <li key={i} className="flex items-start gap-3 font-inter text-sm text-[#6B6B6B]">
                          <span className="w-1 h-1 rounded-full bg-[#ff535b]/40 mt-2 flex-shrink-0" />
                          {bullet}
                        </li>
                      ))}
                    </ul>
                  )}
                  {'footer' in section && section.footer && (
                    <p className="font-inter text-[#4A4A4A] text-sm leading-relaxed italic border-l-2 border-[#ff535b]/20 pl-4 mt-3">
                      {section.footer}
                    </p>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-16 pt-8 border-t border-white/5 text-center">
          <p className="font-inter text-[#2a2a2a] text-xs">
            © 2025 Darkpost. All rights reserved.
          </p>
          <div className="flex items-center justify-center gap-4 mt-4">
            <Link href="/terms" className="font-inter text-xs text-[#4A4A4A] hover:text-[#ff535b] transition-colors">Terms of Use</Link>
            <span className="text-[#2a2a2a]">·</span>
            <Link href="/" className="font-inter text-xs text-[#4A4A4A] hover:text-[#ff535b] transition-colors">Back to Feed</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
